apiVersion: v1
kind: Namespace
metadata:
  name: ga4-admin
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ga4-admin-sa
  namespace: ga4-admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ga4-admin
  name: ga4-admin-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ga4-admin-rolebinding
  namespace: ga4-admin
subjects:
- kind: ServiceAccount
  name: ga4-admin-sa
  namespace: ga4-admin
roleRef:
  kind: Role
  name: ga4-admin-role
  apiGroup: rbac.authorization.k8s.io

---
# Security Context Constraints for OpenShift (if using OpenShift)
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ga4-admin-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
  - max: 65535
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:ga4-admin:ga4-admin-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret